### ISSUE TITLE
Doc: version badge react component for doc pages is missing after the site refactor

### ISSUE THREAD

**Issue by TomShawn** [apache/cloudberry-site#84]
The component added in https://github.com/cloudberrydb/cloudberrydb-site/pull/57 has been missing after the site refactor. Please add this component back and refine it if needed. Thanks

**Comment by tuhaihe** [comment]
Hi @vitalboyzf PTAL, thanks.

**Comment by tuhaihe** [comment]
Now we can use https://shields.io/ to support this feature, so close this issue.
